services:
  db:
    image: postgres:15-alpine
    container_name: ai_courses_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: ai_courses_backend
    restart: always
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "5000:5000"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?schema=public
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${SERVER_PORT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_GEMINI_API_KEY=${GOOGLE_GEMINI_API_KEY}
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  postgres_data: